<?php

namespace App\Filament\Bureau\Resources\Meetings\Pages;

use App\Enums\BureauAgendaItemKind;
use App\Enums\BureauAgendaStatus;
use App\Filament\Bureau\Resources\Meetings\MeetingResource;
use App\Filament\Bureau\Resources\Meetings\Schemas\MeetingForm;
use App\Models\BureauAgendaItem;
use App\Models\BureauMeeting;
use App\Models\BureauSettings;
use Filament\Actions\Action;
use Filament\Resources\Pages\CreateRecord;

class CreateMeeting extends CreateRecord
{
    protected static string $resource = MeetingResource::class;

    protected static bool $canCreateAnother = false;

    /**
     * @var array<int, int>
     */
    protected array $selectedAgendaItemIds = [];

    protected bool $includeAgendaPassing = true;

    /**
     * @var array<int, int>
     */
    protected array $minutesPassingMeetingIds = [];

    public function getTitle(): string
    {
        return __('bureau.meeting.actions.add');
    }

    protected function getCreateFormAction(): Action
    {
        return parent::getCreateFormAction()->label(__('bureau.meeting.actions.save'));
    }

    protected function getCancelFormAction(): Action
    {
        return parent::getCancelFormAction()->label(__('bureau.meeting.actions.cancel'));
    }

    /**
     * Term number comes from the module's settings, and the meeting
     * number is that type's next number in its own sequence (public
     * and emergency meetings are numbered separately) — neither is
     * picked on the form (see MeetingForm and BureauMeetingSettings).
     */
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data = MeetingForm::combineScheduledAt($data);

        $data['created_by'] = auth()->id();
        $settings = BureauSettings::current();
        $data['term_number'] = $settings->current_term_number;
        $data['meeting_number'] = $settings->nextMeetingNumberFor($data['type'] ?? null);
        $data['name'] = BureauMeeting::buildName($data['term_number'], $data['meeting_number'], $data['type'] ?? null);

        // None of these three are BureauMeeting columns — captured here
        // for afterCreate() and dropped so they aren't passed to the
        // model (see MeetingForm's agenda_item_ids, include_agenda_passing,
        // and minutes_passing_meeting_ids fields).
        $this->selectedAgendaItemIds = $data['agenda_item_ids'] ?? [];
        $this->includeAgendaPassing = (bool) ($data['include_agenda_passing'] ?? true);
        $this->minutesPassingMeetingIds = $data['minutes_passing_meeting_ids'] ?? [];
        unset($data['agenda_item_ids'], $data['include_agenda_passing'], $data['minutes_passing_meeting_ids']);

        return $data;
    }

    /**
     * Attaches whichever approved-and-unclaimed agenda items the
     * Bureau Admin left selected on the form (defaults to all of them,
     * see MeetingForm's agenda_item_ids field and
     * BureauAgendaItem::scopeAvailableForMeeting()). Status moves to
     * AddedToMeeting so that's visible directly instead of only
     * inferable from meeting_id being set.
     *
     * The procedural Agenda Passing / Minutes Passing items are created
     * (not claimed from a pool) before the regular items below, so they
     * get lower ids and appear first in $meeting->agendaItems — matching
     * the real order of business (pass this agenda, pass prior minutes,
     * then everything else). Both are auto-approved straight to
     * AddedToMeeting since they're generated by the act of creating the
     * meeting itself, not proposed through the normal review flow — see
     * App\Enums\BureauAgendaItemKind.
     *
     * The settings counter only advances once the meeting is actually
     * persisted, so a validation failure earlier in the request doesn't
     * burn a meeting number.
     */
    protected function afterCreate(): void
    {
        BureauSettings::current()->incrementMeetingNumberFor($this->record->type);

        if ($this->includeAgendaPassing) {
            BureauAgendaItem::create([
                'meeting_id' => $this->record->id,
                'kind' => BureauAgendaItemKind::AgendaPassing,
                'details' => __('bureau.agenda.kind.agenda_passing_details'),
                'status' => BureauAgendaStatus::AddedToMeeting,
                'created_by' => auth()->id(),
                'reviewed_by' => auth()->id(),
                'reviewed_at' => now(),
            ]);
        }

        foreach (BureauMeeting::whereIn('id', $this->minutesPassingMeetingIds)->get() as $pastMeeting) {
            BureauAgendaItem::create([
                'meeting_id' => $this->record->id,
                'kind' => BureauAgendaItemKind::MinutesPassing,
                'related_meeting_id' => $pastMeeting->id,
                'details' => __('bureau.agenda.kind.minutes_passing_details', ['meeting' => $pastMeeting->name]),
                'status' => BureauAgendaStatus::AddedToMeeting,
                'created_by' => auth()->id(),
                'reviewed_by' => auth()->id(),
                'reviewed_at' => now(),
            ]);
        }

        BureauAgendaItem::availableForMeeting()
            ->whereIn('id', $this->selectedAgendaItemIds)
            ->update([
                'meeting_id' => $this->record->id,
                'status' => BureauAgendaStatus::AddedToMeeting,
            ]);
    }
}
